"""Initial migration with fixed metadata column

Revision ID: f4c9abed6783
Revises: 
Create Date: 2025-08-11 17:49:51.113737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c9abed6783'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('salary', sa.String(length=100), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=False),
    sa.Column('benefits', sa.JSON(), nullable=False),
    sa.Column('employment_type', sa.String(length=50), nullable=True),
    sa.Column('experience_level', sa.String(length=50), nullable=True),
    sa.Column('posted_date', sa.DateTime(), nullable=True),
    sa.Column('application_url', sa.String(length=2048), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_clubs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('contact_info', sa.JSON(), nullable=False),
    sa.Column('website', sa.String(length=2048), nullable=True),
    sa.Column('established_date', sa.DateTime(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraping_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('targets', sa.JSON(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('download_url', sa.String(length=2048), nullable=True),
    sa.Column('file_size', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('compatibility', sa.JSON(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraped_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=False),
    sa.Column('scraped_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['scraping_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraping_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('level', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['scraping_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraping_metrics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(length=100), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('metric_unit', sa.String(length=20), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['scraping_jobs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraping_metrics')
    op.drop_table('scraping_logs')
    op.drop_table('scraped_data')
    op.drop_table('support_resources')
    op.drop_table('scraping_jobs')
    op.drop_table('member_clubs')
    op.drop_table('job_listings')
    # ### end Alembic commands ### 